// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq88pA4aorzFwsAzEBxQ1i9wZZSvfgUGc',
    appId: '1:324660483747:web:aea2028d0e6a4ad0995116',
    messagingSenderId: '324660483747',
    projectId: 'club-management-project-43aa4',
    authDomain: 'club-management-project-43aa4.firebaseapp.com',
    storageBucket: 'club-management-project-43aa4.firebasestorage.app',
    measurementId: 'G-B01BW4C045',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oRUhGqwxYfkV7tdwgI31OAuO3zqGqWA',
    appId: '1:324660483747:android:d74f78867639228f995116',
    messagingSenderId: '324660483747',
    projectId: 'club-management-project-43aa4',
    storageBucket: 'club-management-project-43aa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM4p2ubcg_AcomPsZ3lMo1k530MvbXAfg',
    appId: '1:324660483747:ios:01cfdece5aef8557995116',
    messagingSenderId: '324660483747',
    projectId: 'club-management-project-43aa4',
    storageBucket: 'club-management-project-43aa4.firebasestorage.app',
    iosBundleId: 'com.example.clubManagementProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM4p2ubcg_AcomPsZ3lMo1k530MvbXAfg',
    appId: '1:324660483747:ios:01cfdece5aef8557995116',
    messagingSenderId: '324660483747',
    projectId: 'club-management-project-43aa4',
    storageBucket: 'club-management-project-43aa4.firebasestorage.app',
    iosBundleId: 'com.example.clubManagementProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq88pA4aorzFwsAzEBxQ1i9wZZSvfgUGc',
    appId: '1:324660483747:web:259e4f55168d276b995116',
    messagingSenderId: '324660483747',
    projectId: 'club-management-project-43aa4',
    authDomain: 'club-management-project-43aa4.firebaseapp.com',
    storageBucket: 'club-management-project-43aa4.firebasestorage.app',
    measurementId: 'G-Q4N3BNTKG1',
  );
}
